# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Dawn Childress
tagline:             'digital scholarship : book history : textual studies'
description:         'The website of Dawn Childress, Humanities Librarian at Penn State'
url:                 http://dawnchildress.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dawn Childress
  url:               dawnchildress.com
  email:             kirschbombe@gmail.com

# Custom vars
version:             1.0.0
